sudo: required
services:
  - docker

before_install:
  - docker build -t anton_karpenko/create-react-app-with-docker -f Dockerfile.dev .

script:
  - docker run anton_karpenko/create-react-app-with-docker npm run tests -- --coverage
