sudo: required
services:
  - docker

before_install:
  - docker build -t anton_karpenko/create-react-app-with-docker -f Dockerfile.dev .

script:
  - docker run anton_karpenko/create-react-app-with-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test-docker"
  env: "TestDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-896827762451"
  bucket_path: "test-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"